Console.Write("Введите коородинату Х1:");
double x1 = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите коородинату Y1:");
double y1 = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите коородинату Z1:");
double z1 = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите коородинату Х2:");
double x2 = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите коородинату Y2:");
double y2 = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите коородинату Z2:");
double z2 = Convert.ToDouble(Console.ReadLine());
double R = Math.Sqrt(Math.Pow(x2 - x1, 2) + Math.Pow(y2 - y1, 2) + Math.Pow(z2 - z1, 2));
Console.WriteLine($"Расстояние между двумя точками в пространстве равно {Math.Round (R,2)}");
